import GpuDsl.Core

namespace GpuDsl

/-- Ceiling division, used to launch partial edge tiles. -/
def ceilDiv (n tile : Nat) : Nat := (n + tile - 1) / tile

/-- Coordinates generated by perfect tiling are in bounds without a guard. -/
theorem tiledIndex_lt (block : Fin blocks) (thread : Fin tile)
    (perfect : blocks * tile = size) :
    block.val * tile + thread.val < size := by
  calc
    block.val * tile + thread.val < block.val * tile + tile :=
      Nat.add_lt_add_left thread.isLt _
    _ = (block.val + 1) * tile := by
      simp [Nat.add_mul, Nat.add_comm]
    _ ≤ blocks * tile :=
      Nat.mul_le_mul_right tile (Nat.succ_le_of_lt block.isLt)
    _ = size := perfect

end GpuDsl
